[package]
name = "rostra-p2p"
description = "Iroh transport and RPC support for the Rostra protocol"
edition = { workspace = true }
rust-version = { workspace = true }
license = "MIT OR Apache-2.0 OR MPL-2.0"
version = { workspace = true }
repository = "https://github.com/dpc/rostra"
homepage = "https://rostra.me"
documentation = "https://docs.rs/rostra-p2p"
readme = "README.md"
keywords = ["rostra", "p2p", "iroh", "networking"]
categories = ["asynchronous", "network-programming"]
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-MPL",
  "src/**",
]

[dependencies]
anyhow = { workspace = true }
bao-tree = { workspace = true }
bincode = { workspace = true }
convi = { workspace = true }
data-encoding = { workspace = true }
futures = { workspace = true }
iroh-io = { workspace = true }
iroh = { workspace = true }
pkarr = { workspace = true, features = ["dht", "relays"] }
rostra-core = { workspace = true, features = ["bincode", "ed25519-dalek"] }
rostra-util-error = { workspace = true }
serde = { workspace = true, optional = true }
snafu = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true
