[package]
name = "rostra-core"
description = "Signed event graph types for the Rostra protocol"
edition = { workspace = true }
license = "MIT OR Apache-2.0 OR MPL-2.0"
version = { workspace = true }
repository = "https://github.com/dpc/rostra"
homepage = "https://rostra.me"
documentation = "https://docs.rs/rostra-core"
readme = "README.md"
keywords = ["rostra", "p2p", "event", "cryptography"]
categories = ["cryptography", "data-structures"]
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-MPL",
  "benches/**",
  "src/**",
]

[features]
default = []
bincode = ["dep:bincode"]
ed25519-dalek = ["dep:ed25519-dalek", "dep:rand"]
serde = [
  "dep:serde",
  "dep:serde_json",
  "dep:bip39",
  "dep:serde_bytes",
  # "dep:ciborium",
  "dep:cbor4ii",
  "cbor4ii/serde1",
  "cbor4ii/use_std",
]
rand = ["dep:rand", "ed25519-dalek?/rand_core"]

[[bench]]
name = "event"
harness = false

[dependencies]
bech32 = { workspace = true }
bincode = { workspace = true, optional = true }
bip39 = { workspace = true, optional = true }
blake3 = { workspace = true }
bon = { workspace = true }
convi = { workspace = true }
data-encoding = { workspace = true }
ed25519-dalek = { workspace = true, optional = true }
rand = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
serde_json = { workspace = true, optional = true }
serde_bytes = { workspace = true, optional = true }
# ciborium = { workspace = true, optional = true }
cbor4ii = { workspace = true, optional = true, features = ["serde1"] }
snafu = { workspace = true }
pkarr = { workspace = true, optional = true }
time = { workspace = true }
unicode-segmentation = { workspace = true }
url = { workspace = true, features = ["serde"] }
z32 = { workspace = true }

[dev-dependencies]
divan = { workspace = true }
test-log = { workspace = true, features = ["trace"] }
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
