[package]
name = "rostra-util-dedup-chan"
description = "Deduplicating multi-receiver work channel"
edition = { workspace = true }
license = "MIT OR Apache-2.0 OR MPL-2.0"
version = { workspace = true }
repository = "https://github.com/dpc/rostra"
homepage = "https://rostra.me"
documentation = "https://docs.rs/rostra-util-dedup-chan"
readme = "README.md"
keywords = ["rostra", "channel", "deduplication", "tokio"]
categories = ["asynchronous"]
include = [
  "Cargo.toml",
  "README.md",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "LICENSE-MPL",
  "src/**",
]

[features]
default = []

[dependencies]
snafu = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
test-log = { workspace = true, features = ["trace"] }

[lints]
workspace = true
